---
title: Public Speaking, Talks, and Presentations
excerpt: "A list of my selected public speaking activities."
toc-location: right
---

Here's a list of my selected public speaking occasions, talks, and presentations where I was involved.
If available, you'll also find slides, related papers, and recordings.
**Bold** font indicates presenter.

- **Schmitt, M.** (2023). Talk: [Towards Reliable Amortized Bayesian Inference](pdf/slides_reliable_abi_botb.pdf). First presented at the [Bayes on the Beach 2024](https://research.qut.edu.au/qutcds/bayes-onthe-beach/) conference.

- Schmitt, M., **Bürkner, P.-C.** (2024). Workshop: [Amortized Bayesian Inference with BayesFlow](https://colab.research.google.com/drive/1ub9SivzBI5fMbSTwVM1pABsMlRupgqRb?usp=sharing). First presented at the [Bayes on the Beach 2024](https://research.qut.edu.au/qutcds/bayes-onthe-beach/) conference.

- **Schmitt, M.**, Habermann, D., Bürkner, P. C., & Radev, S. T. (2023). 
Talk: [Leveraging Self-Consistency for Data-Efficient Amortized Bayesian Inference](pdf/slides_self_consistency_unireps.pdf). 
First presented at the [NeurIPS Workshop for Unifying Representations in Neural Models](https://neurips.cc/virtual/2023/workshop/66494).
Preprint available on [ArXiv](https://arxiv.org/abs/2310.04395).

- **Schmitt, M.** (2023). Research talk (invited): Jointly Amortized Bayesian Inference, Machine and Human Intelligence group, University of
Helsinki & Finnish Center for Artificial Intelligence (FCAI), Finland

- **Schmitt, M.**, Bürkner, P. C., Köthe, U., & Radev, S. T. (2023). 
Talk (oral): [Detecting Model Misspecification in Amortized Bayesian Inference with Neural Networks](pdf/slides_detecting_mms_gcpr.pdf). 
First presented at the [German Conference on Pattern Recognition](https://www.dagm-gcpr.de/year/2023). 
Paper published in [GCPR Conference Proceedings](https://arxiv.org/abs/2112.08866) (best paper honorable mention). 
Previously featured also as a [poster](pdf/poster_detecting_mms.pdf) and [short talk](pdf/slides_detecting_mms_lightning).

- **Schmitt, M.** (2023). Talk (contributed): Amortized Simulation‑Based Inference, Tooling Session, ELLIS Doctoral Symposium, Helsinki,
Finland

- **Schmitt, M.**, Radev, S. T., & Bürkner, P. C. (2023). 
Poster: [Meta-Uncertainty in Bayesian Model Comparison](pdf/poster_meta_uncertainty.pdf). 
First presented at [AISTATS 2023](http://aistats.org/aistats2023/).
Paper published in [AISSTATS Conference Proceedings](https://proceedings.mlr.press/v206/schmitt23a.html).

{{< video https://www.youtube.com/embed/WIigoUaqy9c 
    title="Meta-Uncertainty in Bayesian Model Comparison (AISTATS 2023)"
    aspect-ratio="16x9" >}}

- **Schmitt, M.** (2023). Talk (invited): What is AI?, Writing workshop for AI short stories, Cyber Valley, Tübingen, Germany

- **Schmitt, M.** (2023). Talk (invited): Where Does AI begin?, Cyber Valley Office hours (general public audience), Tübingen, Germany

- **Schmitt, M.** (2023). Talk (invited): Validating synthetic training data in probabilistic machine learning, Blue Yonder Group Inc., Karlsruhe, Germany
