project:
  type: website

website:
  title: "Marvin Schmitt"
  description: "Marvin Schmitt is a Data & Computer Scientist and Psychologist, currently working as a PhD researcher in Bayesian Statistics and Probabilisitic Machine Learning."
  google-analytics: "G-N36VLTEM79"
  cookie-consent: true
  search: 
    location: navbar
    type: textbox
  navbar:
    left:
      - text: Blog
        href: blog/index.qmd
      - text: Projects
        href: projects/index.qmd
      - text: About Me
        href: index.qmd
    right:
      - icon: twitter
        href: https://twitter.com/MarvinSchmittML
      - icon: linkedin
        href: https://www.linkedin.com/in/marvin-schmitt-a85b321a2/
      - icon: github
        href: https://github.com/marvinschmitt
      - icon: mastodon
        href: https://mastodon.online/@MarvinSchmitt
  favicon: img/favicon.ico
  twitter-card: 
    creator: "@MarvinSchmittML"
    image: img/marvin_foto.png
  site-url: https://www.marvinschmitt.com
  page-footer: 
    left: "Copyright 2023, Marvin Schmitt" 
    right: 
      - text: Impressum
        href: impressum/index.qmd
  comments:
    giscus:
      repo: marvinschmitt/marvinschmitt-dot-com
      category: Announcements
      loading: lazy
      input-position: bottom
      language: en
  
format:
  html:
    fontsize: 1.2em
    theme:
      light: flatly
      dark: darkly
    css: styles.css