project:
  type: website

website:
  title: "Marvin Schmitt"
  google-analytics: "G-N36VLTEM79"
  cookie-consent: true
  navbar:
    right:
      - text: Blog
        href: blog/index.qmd
      - text: Projects
        href: projects/index.qmd
      - text: About Me
        href: index.qmd
      - icon: twitter
        href: https://twitter.com/MarvinSchmittML
      - icon: linkedin
        href: https://www.linkedin.com/in/marvin-schmitt-a85b321a2/
      - icon: github
        href: https://github.com/marvinschmitt
      - icon: mastodon
        href: https://mastodon.online/@MarvinSchmitt
  favicon: img/favicon.ico
  twitter-card: true
  site-url: https://www.marvinschmitt.com
  page-footer: 
    left: "Copyright 2023, Marvin Schmitt" 
    right: 
      - text: Impressum
        href: impressum/index.qmd
  
format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css